version: "3"
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./build/nginx        
            dockerfile: Dockerfile
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/ssl/private:/etc/ssl/private
            - ./etc/ssl/certs:/etc/ssl/certs
            - ./var/www/localhost/public_html:/usr/share/nginx/html
            - ./var/log/nginx:/var/log/nginx
        ports:
            - 80:80
#            - 443:443         
        networks:
            - nginx-network

networks:
    nginx-network:
        driver: bridge
